remote_control_options:
  - label: "邀请IT-唐林钰远程控制"
    username: "tanglingyu"
    type: "IT"
    action: "request"
  - label: "邀请TD-冯青青远程控制"
    username: "fengqingqing"
    type: "TD"
    action: "request"
  - label: "邀请TA-刘作远程控制"
    username: "liuzuo"
    type: "TA"
    action: "request"
  - label: "邀请TA-张群忠远程控制"
    username: "zhangqunzhong"
    type: "TA"
    action: "request"
  - label: "邀请TA-翟文朋远程控制"
    username: "zhaiwenpeng"
    type: "TA"
    action: "request"
  - label: "邀请OC1-60_服务器远程控制"
    username: "OC1"
    type: "Server"
    action: "request"
  - label: "控制26号机器"
    type: "vnc"
    action: "connect"
    host: "192.168.110.26"
    port: 5900
    password: "OC.123456"
  - label: "控制61号机器"
    type: "vnc"
    action: "connect"
    host: "192.168.110.61"
    port: 5900
    password: "OC.123456"
  - label: "控制60号机器"
    type: "vnc"
    action: "connect"
    host: "192.168.110.60"
    port: 5900
    password: "OC.123456"
  - label: "控制27号机器"
    type: "vnc"
    action: "connect"
    host: "192.168.110.27"
    port: 5900
    password: "OC.123456"
  - label: "控制25号机器"
    type: "vnc"
    action: "connect"
    host: "192.168.111.25"
    port: 5900
    password: "OC.123456"
  - label: "控制186号机器"
    type: "vnc"
    action: "connect"
    host: "192.168.111.186"
    port: 5900
    password: "OC.123456"
  - label: "控制135号机器"
    type: "vnc"
    action: "connect"
    host: "192.168.111.135"
    port: 5900
    password: "OC.123456"
  - label: "控制253号机器"
    type: "vnc"
    action: "connect"
    host: "192.168.111.253"
    port: 5900
    password: "OC.123456"
  - label: "控制71号机器"
    type: "vnc"
    action: "connect"
    host: "192.168.111.71"
    port: 5900
    password: "OC.123456"
